# Generated by Django 4.1.7 on 2023-03-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='users'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.CharField(blank=True, default=' ', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
