# Generated by Django 4.1.7 on 2023-03-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_song_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='qwe', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='qwe', max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(default='qwe', max_length=255, unique=True),
        ),
    ]
