# Generated by Django 4.1.7 on 2023-03-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_profile_name_alter_profile_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default/default-avatar.jpg', upload_to='profiles/%Y/%m/%d/'),
        ),
    ]
