# Generated by Django 4.1.7 on 2023-03-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='media/default/default-avatar.jpg', upload_to='profiles/%Y/%m/%d/'),
        ),
    ]
