# Generated by Django 4.1.7 on 2023-03-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='playlist',
        ),
        migrations.AddField(
            model_name='playlist',
            name='song',
            field=models.ManyToManyField(related_name='playlist_songs', to='music.song'),
        ),
    ]
