# Generated by Django 4.1.7 on 2023-03-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_genre_song_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_genres',
            field=models.ManyToManyField(blank=True, null=True, related_name='profile_genres', to='music.genre'),
        ),
    ]
