# Generated by Django 4.1.7 on 2023-03-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_profile_favorite_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_genres',
            field=models.ManyToManyField(blank=True, related_name='profile_genres', to='music.genre'),
        ),
    ]
