# Generated by Django 4.1.7 on 2023-04-05 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0012_alter_profile_favorite_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='image_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
