# Generated by Django 4.1.7 on 2023-04-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_song_users_like_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
