# Generated by Django 4.1.7 on 2023-04-08 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0014_alter_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayListHearingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heared_playlist', to='music.playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_hearing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
